name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Check out to another path
        uses: actions/checkout@v6
        with:
          path: default

      - name: Check out head.sha
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: head.sha

      - name: Check out merge_commit_sha
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          path: merge_commit_sha

      - name: Get current working dir1
        run: |
          echo '------------------------ pwd -------------------------'
          echo "$(pwd)"
          echo '-------------------- files in pwd --------------------'
          ls
          echo '-------------- diff -r default head.sha --------------'
          diff -r default head.sha
          echo '-------------- diff -r default merge_commit_sha --------------'
          diff -r default merge_commit_sha
          echo '-------------- diff -r head.sha merge_commit_sha --------------'
          diff -r head.sha merge_commit_sha
