name: test

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Check out to another path
        uses: actions/checkout@v6
        with:
          path: default

      - name: Check out refs/pull/PR_NUM/head
        uses: actions/checkout@v6
        with:
          ref: refs/pull/${{ github.event.number }}/head
          path: head

      - name: Check out refs/pull/PR_NUM/merge
        uses: actions/checkout@v6
        with:
          ref: refs/pull/${{ github.event.number }}/merge
          path: merge

      - name: Get current working dir1
        run: |
          echo '------------------------ pwd -------------------------'
          echo "$(pwd)"
          echo '-------------------- files in pwd --------------------'
          ls
          echo '---------------- diff -r default head ----------------'
          diff -r -x .git default head || true
          echo '---------------- diff -r default merge ---------------'
          diff -r -x .git default merge || true
          echo '----------------- diff -r head merge -----------------'
          diff -r -x .git head merge || true

      - name: Get secret
        run: |
          echo '${{ secrets.MY_SECRET }}'

      - name: Change dir
        run: cd merge

      - name: Check pwd
        run: pwd

      - name: Check event number
        env:
          EVENT_NUMBER1: ${{ format('pr_{0}', github.event.number) }}
          EVENT_NUMBER2: >
            ${{
                format('pr_{0}', github.event.number)
            }}
        run: |
          echo '--------- EVENT_NUMBER1 ---------'
          echo "${EVENT_NUMBER1}"
          echo '--------- EVENT_NUMBER1 ---------'
          echo "${EVENT_NUMBER2}"
          echo '---------------------------------'
